### ISSUE TITLE
RemovedInDjango40Warning

### ISSUE THREAD

**Issue by amitassaraf** [anexia-it/django-rest-passwordreset#95]
Using this library in Django 3.0+ yields a few RemovedInDjango40Warning warnings:

```
RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
  verbose_name = _("Password Reset Token")
....
```

**Comment by anx-cbenke** [comment]
This has finally been fixed in #83

**Comment by christianbos** [comment]
Hi, im installing the package with `pip install django-rest-passwordreset` but this warning still appearing, the package code has the `.ugettext_lazy()` method. Any idea of what happen?
